name: sora-watermark-remover
services:
- name: backend
  source_dir: /backend
  github:
    repo: your-username/sora-watermark-remover
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${redis.REDIS_URL}
  - key: SECRET_KEY
    scope: RUN_TIME
    value: your-production-secret-key
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    value: your-aws-key
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    value: your-aws-secret
  - key: AWS_REGION
    scope: RUN_TIME
    value: us-east-1
  - key: S3_BUCKET_NAME
    scope: RUN_TIME
    value: your-bucket-name

- name: frontend
  source_dir: /frontend
  github:
    repo: your-username/sora-watermark-remover
    branch: main
  build_command: npm ci && npm run build
  run_command: npx serve -s build -l 3000
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: REACT_APP_API_URL
    scope: RUN_TIME
    value: ${backend.PUBLIC_URL}

databases:
- name: db
  engine: PG
  version: "13"
  size: db-s-dev-database

- name: redis
  engine: REDIS
  version: "6"
  size: db-s-dev-database
